name: 09 - Using Functions

on: 
    workflow_dispatch:

jobs: 
    echo1:
        runs-on: ubuntu-latest
        steps:     
            - name: I will execute
              if: ${{ failure()}}
              run: echo "I will print if previous steps fail"
            - name: I will execute
              if: ${{ !cancelled() }}
              run: echo "I will print it always, except when the workflow is cancelled."
            - name: I will execute when cancelled
              if: ${{ cancelled() }}
              run: echo "I will print it only when the workflow has been cancelled."